---
title: "shiny"
author: "Franky Zhang"
date: "11/2/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
Sys.setenv("LANGUAGE" = "EN")
Sys.setlocale("LC_ALL", "C")
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(magrittr)
library(shiny)
library(maps)
```

```{r}

strb <- read.csv("strawberry_test.csv")

drop_no_info_cols <- function(df){
  cnames <- colnames(df)
  T = NULL
  for(i in 1:ncol(df)){T <- c(T, nrow(unique(df[i])))} # unique values of each column
  drop_cols <- cnames[which(T == 1)]
  return(select(df, !all_of(drop_cols)))
}

strb <- drop_no_info_cols(strb)
strb %<>% separate(col = Data.Item, 
                   into = c("Strawberries", "items", "discription", "units"), 
                   sep = ",", 
                   fill = "right")
strb %<>% 
  mutate(Chemicals = Domain.Category) %>% 
  relocate(Chemicals, .after = Domain.Category)

strb %<>% separate(col = Chemicals,
                     into = c("chemical.type", "chemical"),
                     sep = ":",
                     fill = "right")


strb$chemical <- str_extract(str_trim(strb$chemical) ,"[^(].*[^)]")
strb %<>% separate(col = chemical, 
                    into = c("chemical", "che_num"), 
                    sep = "=", 
                    fill = "right")
pest <- read.csv("pesticides.csv")
names(pest)[1] <- "Pesticide"

pest <- pest[!apply(pest == "",1, all), ] # delete empty rows
# include empty relationship
l_pest <- pest %>% gather(Toxicity, Level, Carcinogen:Bee.Toxins, -Pesticide)

# clarify a new column, human or bee
l_pest <- mutate(l_pest, humanORbee = ifelse(Toxicity == "Bee.Toxins", "Bee", "Human"))

# without empty relationship
rela_pest <- l_pest[!(l_pest$Level == ""), ]

# turn name into capital letters
rela_pest$Pesticide <- toupper(rela_pest$Pesticide)

names(rela_pest)[1] <- "chemical"

strb$chemical <- str_trim(strb$chemical)
strb$discription <- str_trim(strb$discription)
# count(strb, chemical.type)
df <- merge(x= strb, y = rela_pest, by = "chemical")
# count(df, chemical.type)

df %<>% select(chemical, chemical.type, humanORbee, Level, State, Year, discription, Value, Year,  Toxicity)

df %<>% filter(!Value == " (D)" & !Value == " (Z)")

df %<>% filter(discription == "MEASURED IN LB / ACRE / APPLICATION")
df <- drop_no_info_cols(df)

df$Value <- as.numeric(df$Value)
df$Year <- as.factor(df$Year)
df$chemical.type <- as.factor(df$chemical.type)
df %>%count(State)
df$Value_q <- as.factor(ifelse((df$Value <= .1420), "0.0010 ~ 0.1420", 
                     ifelse((df$Value > .1420 & df$Value <= .8004), "0.1420 ~ 0.8004", 
                            ifelse((df$Value > .8004 & df$Value <= 1.0900), "0.8004 ~ 1.0900", "1.0900 ~ 3.0900" ))))

mu <- df %>% group_by(chemical.type) %>% summarise(mean = mean(Value))

```

```{r}
# point plot
ui_1 <- fluidPage(
  selectInput("chemical.type", "select the chemical type", c("CHEMICAL, INSECTICIDE", "CHEMICAL, FUNGICIDE")),
  selectInput("State", "select state", unique(df$State)),
  plotOutput("plot", brush = "plot_brush"),
  tableOutput("data")
)
server_1 <- function(input, output, session) {
  output$plot <- renderPlot({
    ggplot(data = subset(df, chemical.type == input$chemical.type & State == input$State),
           mapping = aes(x = Year, y = Value, color = chemical)) + 
      geom_point()
    }, res = 96)
  
  output$data <- renderTable({
    brushedPoints(subset(df, chemical.type == input$chemical.type & State == input$State), input$plot_brush)
  })
}

shinyApp(ui_1, server_1)

```



```{r}
# map
year <- df %>% distinct(Year)
year <- year$Year
MainStates <- map_data("state")
MainStates$region <- toupper(MainStates$region)
colnames(MainStates) <- c("long", "lat", "group", "order", "State", "subregion")
MainStates$State <- toupper(MainStates$State)

# df_mean <- df %>% group_by(State) %>% summarise(mean_value = mean(Value))
# plot_data <- inner_join(df_mean, MainStates, by = "State")

ui_2 <- fluidPage(
  selectInput("Year", "select year", year), 
  plotOutput("plot")
)
server_2 <- function(input, output, session) {
    output$plot <- renderPlot({
    df_mean <- df %>% subset(Year == input$Year) %>% group_by(State) %>% summarise(mean_value = mean(Value))
    plot_data <- inner_join(df_mean, MainStates, by = "State") %>% 
      select(c("State", "long", "lat", "mean_value", "group"))
    ggplot() + 
    geom_polygon(data=MainStates, aes(x=long, y=lat, group=group),color="black", fill="seashell1", size = .3) + 
    geom_polygon(data = plot_data, aes(x = long, y = lat, group = group, fill = mean_value), 
               color = "grey", size = .3) + 
    scale_fill_continuous(name="strawberry value", 
            low = "blue2", 
            high = "brown3", 
            na.value = "grey50") + labs(title="Strawberry values(MEASURED IN LB / ACRE / APPLICATION)")
    }, res = 96, height = 550, width = 950)
}

shinyApp(ui_2, server_2)
  
```